yaml
name: tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Instalar Google Chrome
        uses: browser-actions/setup-chrome@v1
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Ejecutar tests
        run: pytest -m smoke --alluredir=allure-results
      - name: Subir resultados Allure
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
