name: tests

on: 
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ejecutar tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -m smoke --alluredir=allure-results

      - name: Subir resultados Allure
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
